/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ASUS ROG
 */
public class EstudianteDatosAcademicos extends javax.swing.JPanel {

    /**
     * Creates new form EstudianteDatos
     */
    private Dashboard vistaPrincipal;

    public EstudianteDatosAcademicos(Dashboard vistaPrincipal) {
        this.vistaPrincipal = vistaPrincipal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        panel_datosAcademicos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_ciclo = new javax.swing.JTextField();
        chk_alumnoObservado = new javax.swing.JCheckBox();
        chk_alumnoNoObservado = new javax.swing.JCheckBox();
        txt_codigo = new javax.swing.JTextField();
        txt_ponderado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_siguiente_2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        panel_datosAcademicos.setBackground(new java.awt.Color(255, 255, 255));
        panel_datosAcademicos.setPreferredSize(new java.awt.Dimension(0, 539));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Digite su promedio ponderado *");

        chk_alumnoObservado.setBackground(new java.awt.Color(255, 255, 255));
        chk_alumnoObservado.setForeground(new java.awt.Color(0, 0, 0));
        chk_alumnoObservado.setText("Si");
        chk_alumnoObservado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_alumnoObservadoActionPerformed(evt);
            }
        });

        chk_alumnoNoObservado.setBackground(new java.awt.Color(255, 255, 255));
        chk_alumnoNoObservado.setForeground(new java.awt.Color(0, 0, 0));
        chk_alumnoNoObservado.setText("No");

        txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("¿En qué ciclo se encuentra?");

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("¿Es usted un alumno observado? *");

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Recuerde que será verificado mediante los sustentos");

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Digite su codigo de estudiante *");

        btn_siguiente_2.setBackground(new java.awt.Color(21, 101, 192));
        btn_siguiente_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_siguiente_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_siguiente_2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_siguiente_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_siguiente_2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_siguiente_2MousePressed(evt);
            }
        });
        btn_siguiente_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        btn_siguiente_2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Siguiente");
        btn_siguiente_2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        javax.swing.GroupLayout panel_datosAcademicosLayout = new javax.swing.GroupLayout(panel_datosAcademicos);
        panel_datosAcademicos.setLayout(panel_datosAcademicosLayout);
        panel_datosAcademicosLayout.setHorizontalGroup(
            panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(txt_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(chk_alumnoObservado)
                        .addGap(127, 127, 127)
                        .addComponent(chk_alumnoNoObservado))
                    .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1))
                    .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_ponderado, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(402, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datosAcademicosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_siguiente_2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jLabel7)
                    .addContainerGap(451, Short.MAX_VALUE)))
            .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jLabel8)
                    .addContainerGap(319, Short.MAX_VALUE)))
            .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(jLabel9)
                    .addContainerGap(457, Short.MAX_VALUE)))
        );
        panel_datosAcademicosLayout.setVerticalGroup(
            panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datosAcademicosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chk_alumnoNoObservado)
                            .addComponent(chk_alumnoObservado))))
                .addGap(58, 58, 58)
                .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txt_ponderado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_siguiente_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                    .addGap(133, 133, 133)
                    .addComponent(jLabel7)
                    .addContainerGap(388, Short.MAX_VALUE)))
            .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(346, Short.MAX_VALUE)))
            .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                    .addGap(286, 286, 286)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(235, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_datosAcademicos, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_datosAcademicos, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chk_alumnoObservadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_alumnoObservadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_alumnoObservadoActionPerformed

    private void txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

    }//GEN-LAST:event_jLabel2MouseClicked

    private void btn_siguiente_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_siguiente_2MouseClicked
         vistaPrincipal.mostrarPanel("datosRequisitos");
    }//GEN-LAST:event_btn_siguiente_2MouseClicked

    private void btn_siguiente_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_siguiente_2MouseEntered

    }//GEN-LAST:event_btn_siguiente_2MouseEntered

    private void btn_siguiente_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_siguiente_2MouseExited

    }//GEN-LAST:event_btn_siguiente_2MouseExited

    private void btn_siguiente_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_siguiente_2MousePressed
        vistaPrincipal.mostrarPanel("datosRequisitos");
    }//GEN-LAST:event_btn_siguiente_2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_siguiente_2;
    private javax.swing.JCheckBox chk_alumnoNoObservado;
    private javax.swing.JCheckBox chk_alumnoObservado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel panel_datosAcademicos;
    private javax.swing.JTextField txt_ciclo;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_ponderado;
    // End of variables declaration//GEN-END:variables
}
