/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_admin1;

import BD.DAOEstudiante;
import BD.DAOPostulante;
import estructura.Cola;
import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Estudiante;


/**
 *
 * @author ASUS ROG
 */
public class ControlPostulantes1 extends javax.swing.JFrame {

    /**
     * Creates new form ControlPostulantes1
     */
    VisualizarPostulantes pnl_vizualizarP = new VisualizarPostulantes(this);
    ControlSeleccionados controlSeleccionados = new ControlSeleccionados(this);
    CardLayout vista;

    VisualizarPostulantes v = new VisualizarPostulantes(this);
    Cola<Estudiante> colaAprobados;

    public ControlPostulantes1() {
        initComponents();
        //Inicializamos en el constructor el 'colaAprobados' para que se pueda acceder en otros paneles
        colaAprobados = new Cola<>();
        //Configuracion para acceder entre paneles
        vista = (CardLayout) pnl_vistaP.getLayout();
        SwingUtilities.updateComponentTreeUI(this);
        this.revalidate();
        this.repaint();
        pnl_vistaP.add(pnl_vizualizarP, "visualizarPostulantes");
        pnl_vistaP.add(controlSeleccionados, "ControlSeleccionados");
    }
    // Método para manejar el clic en deshacer

    public Cola<Estudiante> getColaAprobados() {
        return colaAprobados;
    }

    private void volverAlPanel(JPanel panel, String panel1) {
        pnl_vistaP.add(panel, panel1);
        vista.show(pnl_vistaP, panel1);
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }

    public void mostrarPanel(String nombrePanel) {
        CardLayout cardLayout = (CardLayout) pnl_vistaP.getLayout();
        cardLayout.show(pnl_vistaP, nombrePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_personales = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_personales1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnl_vistaP = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(165, 165, 141));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Poppins", 2, 17)); // NOI18N
        jLabel1.setText("Control de Postulantes");

        btn_personales.setBackground(new java.awt.Color(107, 112, 92));
        btn_personales.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_personales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_personalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_personalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_personalesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_personalesMousePressed(evt);
            }
        });
        btn_personales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_personales.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Visualizar postulantes");
        btn_personales.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        btn_personales1.setBackground(new java.awt.Color(107, 112, 92));
        btn_personales1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_personales1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_personales1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_personales1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_personales1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_personales1MousePressed(evt);
            }
        });
        btn_personales1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_personales1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Postulantes seleccionados");
        btn_personales1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_personales, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_personales1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(177, 177, 177)
                .addComponent(btn_personales, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_personales1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_vistaP.setBackground(new java.awt.Color(183, 183, 164));
        pnl_vistaP.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_vistaP, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_vistaP, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_personalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_personalesMouseClicked

        volverAlPanel(pnl_vizualizarP, "visualizarPostulantes");

    }//GEN-LAST:event_btn_personalesMouseClicked

    private void btn_personalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_personalesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_personalesMouseEntered

    private void btn_personalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_personalesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_personalesMouseExited

    private void btn_personalesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_personalesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_personalesMousePressed

    private void btn_personales1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_personales1MouseClicked
        volverAlPanel(controlSeleccionados, "ControlSeleccionados");
    }//GEN-LAST:event_btn_personales1MouseClicked

    private void btn_personales1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_personales1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_personales1MouseEntered

    private void btn_personales1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_personales1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_personales1MouseExited

    private void btn_personales1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_personales1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_personales1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPostulantes1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPostulantes1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPostulantes1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPostulantes1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlPostulantes1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_personales;
    private javax.swing.JPanel btn_personales1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnl_vistaP;
    // End of variables declaration//GEN-END:variables
}
