/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_postulante;

import controlador.GestorDeNavegacion;
import controlador.controlador_estudiante;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import model.Estudiante;

/**
 *
 * @author ASUS ROG
 */
public class EstudianteDatosAcademicos extends javax.swing.JPanel {

    /**
     * Creates new form EstudianteDatos
     */
    private Dashboard vistaPrincipal;
    private controlador_estudiante controlador;

    public EstudianteDatosAcademicos(Dashboard vistaPrincipal) {
        this.vistaPrincipal = vistaPrincipal;
        controlador = new controlador_estudiante(vistaPrincipal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_observado = new javax.swing.ButtonGroup();
        panel_datosAcademicos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_ciclo = new javax.swing.JTextField();
        txt_codigo = new javax.swing.JTextField();
        txt_ponderado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_siguiente_2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        r_observado = new javax.swing.JRadioButton();
        r_noObservado = new javax.swing.JRadioButton();
        btn_anterior = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        panel_datosAcademicos.setBackground(new java.awt.Color(255, 255, 255));
        panel_datosAcademicos.setPreferredSize(new java.awt.Dimension(0, 539));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel1.setText("Digite su promedio ponderado *");

        txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setText("¿En qué ciclo se encuentra?");

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setText("¿Es usted un alumno observado? *");

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setText("Recuerde que será verificado mediante los sustentos");

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setText("Digite su codigo de estudiante *");

        btn_siguiente_2.setBackground(new java.awt.Color(21, 101, 192));
        btn_siguiente_2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_siguiente_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_siguiente_2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_siguiente_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_siguiente_2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_siguiente_2MousePressed(evt);
            }
        });
        btn_siguiente_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        btn_siguiente_2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Siguiente");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        btn_siguiente_2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        r_observado.setBackground(new java.awt.Color(255, 255, 255));
        grupo_observado.add(r_observado);
        r_observado.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        r_observado.setText("Si");

        r_noObservado.setBackground(new java.awt.Color(255, 255, 255));
        grupo_observado.add(r_noObservado);
        r_noObservado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        r_noObservado.setText("No");

        btn_anterior.setBackground(new java.awt.Color(21, 101, 192));
        btn_anterior.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_anteriorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_anteriorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_anteriorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_anteriorMousePressed(evt);
            }
        });
        btn_anterior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        btn_anterior.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Anterior");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        btn_anterior.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        javax.swing.GroupLayout panel_datosAcademicosLayout = new javax.swing.GroupLayout(panel_datosAcademicos);
        panel_datosAcademicos.setLayout(panel_datosAcademicosLayout);
        panel_datosAcademicosLayout.setHorizontalGroup(
            panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datosAcademicosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btn_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_siguiente_2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(txt_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                            .addGap(161, 161, 161)
                            .addComponent(r_observado)
                            .addGap(60, 60, 60)
                            .addComponent(r_noObservado))
                        .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(jLabel1))
                        .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(txt_ponderado, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(402, Short.MAX_VALUE))
            .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jLabel7)
                    .addContainerGap(451, Short.MAX_VALUE)))
            .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jLabel8)
                    .addContainerGap(319, Short.MAX_VALUE)))
            .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(jLabel9)
                    .addContainerGap(457, Short.MAX_VALUE)))
        );
        panel_datosAcademicosLayout.setVerticalGroup(
            panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_noObservado)
                    .addComponent(r_observado))
                .addGap(63, 63, 63)
                .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txt_ponderado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_siguiente_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                    .addGap(133, 133, 133)
                    .addComponent(jLabel7)
                    .addContainerGap(388, Short.MAX_VALUE)))
            .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(346, Short.MAX_VALUE)))
            .addGroup(panel_datosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_datosAcademicosLayout.createSequentialGroup()
                    .addGap(286, 286, 286)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(235, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_datosAcademicos, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_datosAcademicos, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void btn_anteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anteriorMouseClicked
       
      vistaPrincipal.retroceder();
        System.out.println(); 
    }//GEN-LAST:event_btn_anteriorMouseClicked

    private void btn_anteriorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anteriorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_anteriorMouseEntered

    private void btn_anteriorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anteriorMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_anteriorMouseExited

    private void btn_anteriorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anteriorMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_anteriorMousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel2MouseClicked

    }// GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_jLabel5MouseClicked

    private void btn_siguiente_2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_siguiente_2MouseClicked
        int ciclo = Integer.parseInt(txt_ciclo.getText());
        boolean observado = r_observado.isSelected();
        double ponderado = Double.parseDouble(txt_ponderado.getText());

        int puntuacion = puntuacionAcademica(ciclo, observado, ponderado);
        vistaPrincipal.sumarPuntuacion("datosAcademicos",puntuacion);
        
        System.out.println(vistaPrincipal.getPuntuacion());
        System.out.println("");
        controlador.actualizarDatosAcademicos(txt_ciclo, r_observado, r_noObservado, txt_codigo, txt_ponderado);
        // Cambiar al siguiente panel
        vistaPrincipal.mostrarPanel("datosRequisitos");
        GestorDeNavegacion.obtenerInstancia().guardarPanel("datosAcademicos");
    }

    private int puntuacionAcademica(int ciclo, boolean observado, double ponderado) {
        int puntuacion = vistaPrincipal.puntuacion;
        if (ciclo < 6) {
            puntuacion += 10;
        } 
        if (observado) {
            puntuacion -= 10;
        }
        if (ponderado > 17) {
            puntuacion += 15;
        } else if (ponderado < 17 && ponderado >= 16) {
            puntuacion += 10;
        } else if (ponderado < 16 && ponderado >= 15) {
            puntuacion += 5;
        }
        return puntuacion;

    }

    private void btn_siguiente_2MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_siguiente_2MouseEntered

    }// GEN-LAST:event_btn_siguiente_2MouseEntered

    private void btn_siguiente_2MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_siguiente_2MouseExited

    }// GEN-LAST:event_btn_siguiente_2MouseExited

    private void btn_siguiente_2MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_siguiente_2MousePressed

    }// GEN-LAST:event_btn_siguiente_2MousePressed

    private void txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_codigoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txt_codigoActionPerformed

    // GEN-LAST:event_btn_siguiente_2MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_anterior;
    private javax.swing.JPanel btn_siguiente_2;
    private javax.swing.ButtonGroup grupo_observado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panel_datosAcademicos;
    private javax.swing.JRadioButton r_noObservado;
    private javax.swing.JRadioButton r_observado;
    private javax.swing.JTextField txt_ciclo;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_ponderado;
    // End of variables declaration//GEN-END:variables
}
