package vista_postulante;

import BD.Conexion;
import BD.DAOUser;
import controlador.GestorDeNavegacion;
import controlador.controlador_estudiante;
import estructura.ListaEnlazada;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import model.Entrevista;
import model.Estudiante;
import model.SesionUsuario;
import model.Usuario;

public class PanelEst extends javax.swing.JFrame {
    
    int xMouse;
    int yMouse;
    Conexion conn;
    Connection reg;
    /**
     * Creates new form Dashboard
     */

    double puntuacion;
    CardLayout vista;
    Estudiante estudiante;
    private controlador_estudiante controlador;

    ListaEnlazada<Estudiante> lista;
    ListaEnlazada<Entrevista> listaRespuestas;
    login1 login;
    PostularBeca pnl_postular = new PostularBeca(this);
    EstadoSolicitud1 estadoS = new EstadoSolicitud1(this);
    EstadoSolicitudAprobado aprobado = new EstadoSolicitudAprobado(this);
    EstadoSolicitudRechazado rechazado = new EstadoSolicitudRechazado(this);
    PostulanteEntrevista1 e1 = new PostulanteEntrevista1(this);
    PostulanteEntrevista2 e2 = new PostulanteEntrevista2(this);
    PostulanteEntrevista3 e3 = new PostulanteEntrevista3(this);
    Entrevista entrevista;
    public PanelEst() {

        initComponents();
        entrevista = new Entrevista();
        this.login = new login1();
        /*
         * LocalDate now = LocalDate.now();
         * int year = now.getYear();
         * int dia = now.getDayOfMonth();
         * int month = now.getMonthValue();
         */
        vista = (CardLayout) pnl_vistaPrincipal.getLayout();

        pnl_vistaPrincipal.add(pnl_postular, "postularBeca");
        pnl_vistaPrincipal.add(estadoS, "estadoSolicitud");
        pnl_vistaPrincipal.add(aprobado, "Aprobado");
        pnl_vistaPrincipal.add(rechazado, "Rechazado");
        pnl_vistaPrincipal.add(e1 , "respuesta1");
        pnl_vistaPrincipal.add(e2 , "respuesta2");
        pnl_vistaPrincipal.add(e3 , "respuesta3");

    }
    public void retroceder() {
        GestorDeNavegacion.obtenerInstancia().retroceder(vista , pnl_vistaPrincipal);
    }

    public PostulanteEntrevista1 getE1() {
        return e1;
    }

    public PostulanteEntrevista2 getE2() {
        return e2;
    }

    public PostulanteEntrevista3 getE3() {
        return e3;
    }
    
    public Entrevista getEntrevista() {
        return entrevista;
    }

    public void setEntrevista(Entrevista entrevista) {
        this.entrevista = entrevista;
    }
    
    public Estudiante getEstudiante() {
        return estudiante;
    }

    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }

    public ListaEnlazada<Estudiante> getLista() {
        return lista;
    }
    public ListaEnlazada<Entrevista> getRespuestas() {
        return listaRespuestas;
    }

    // Metodo para obtener el panel de la vista principal
    public JPanel getPnlPrincipal() {
        return pnl_vistaPrincipal;
    }

    public void actualizarPuntuacion(double puntos) {
        this.puntuacion += puntos;
    }

    public double getPuntuacion() {
        return puntuacion;
    }

    public void resetPuntuacion() {
        puntuacion = 0;
    }

    public void setDatosBeca(double puntuacion) {
        this.puntuacion = puntuacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        Background = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        btn_requisitos = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        app_name = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_verificar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        Title = new javax.swing.JPanel();
        red_squr = new javax.swing.JPanel();
        pnl_vistaPrincipal = new javax.swing.JPanel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(13, 71, 161));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_requisitos.setBackground(new java.awt.Color(18, 90, 173));
        btn_requisitos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_requisitos.setPreferredSize(new java.awt.Dimension(270, 51));
        btn_requisitos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_requisitosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_requisitosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_requisitosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_requisitosMousePressed(evt);
            }
        });
        btn_requisitos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Realizar Entrevista");
        btn_requisitos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        Menu.add(btn_requisitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        app_name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        app_name.setForeground(new java.awt.Color(255, 255, 255));
        app_name.setText("Opciones ");
        Menu.add(app_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        Menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 190, 20));

        btn_verificar.setBackground(new java.awt.Color(21, 101, 192));
        btn_verificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_verificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_verificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_verificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_verificarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_verificarMousePressed(evt);
            }
        });
        btn_verificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_verificar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Verificar Estado de Peticion");
        btn_verificar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        Menu.add(btn_verificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 270, 50));

        Background.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 720));

        Header.setBackground(new java.awt.Color(25, 118, 210));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Poppins", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SISTEMA DE BECAS");

        exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(102, 102, 102));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        Background.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 610, 120));

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TitleMouseDragged(evt);
            }
        });
        Title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TitleMousePressed(evt);
            }
        });

        red_squr.setBackground(new java.awt.Color(255, 255, 255));
        red_squr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        red_squr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                red_squrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                red_squrMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                red_squrMousePressed(evt);
            }
        });

        javax.swing.GroupLayout red_squrLayout = new javax.swing.GroupLayout(red_squr);
        red_squr.setLayout(red_squrLayout);
        red_squrLayout.setHorizontalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        red_squrLayout.setVerticalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TitleLayout = new javax.swing.GroupLayout(Title);
        Title.setLayout(TitleLayout);
        TitleLayout.setHorizontalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleLayout.createSequentialGroup()
                .addGap(0, 984, Short.MAX_VALUE)
                .addComponent(red_squr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TitleLayout.setVerticalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(red_squr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Background.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        pnl_vistaPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnl_vistaPrincipal.setLayout(new java.awt.CardLayout());
        Background.add(pnl_vistaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 605, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_verificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verificarMouseClicked
        String correo = SesionUsuario.getInstancia().getUsuarioLogueado().getCorreo();
        String estadoPostulante = verificarEstado(correo);
        modificar(estadoPostulante);
        System.out.println(estadoPostulante);

    }//GEN-LAST:event_btn_verificarMouseClicked
    public String verificarEstado(String correo) {
        String estado = "Pendiente"; // Valor predeterminado

        // Consulta SQL para obtener el estado del postulante basado en el correo del usuario
        String sql = "SELECT p.estado FROM postulantes p "
                + "JOIN usuariosEstudiantes u ON p.correo = u.correo "
                + "WHERE u.correo = ?";
        Conexion conexion = new Conexion();
        try (Connection connection = conexion.getConnection();
                PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setString(1, correo);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    estado = resultSet.getString("estado");
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Manejar excepción si es necesario
        }

        return estado;
    }

    public void modificar(String estado) {
        // Este método actualiza la interfaz de usuario según el estado de la solicitud

        switch (estado) {
            case "Aprobado":
                volverAlPanel(aprobado, "Aprobado");

                break;
            case "Pendiente":

                volverAlPanel(estadoS, "estadoSolicitud");

                break;
            default:

                volverAlPanel(rechazado, "Rechazado");

                break;
        }

    }
    private void btn_verificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verificarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_verificarMouseEntered

    private void btn_verificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verificarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_verificarMouseExited

    private void btn_verificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verificarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_verificarMousePressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }// GEN-LAST:event_formWindowActivated

    private void TitleMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TitleMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }// GEN-LAST:event_TitleMousePressed

    private void TitleMouseDragged(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TitleMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }// GEN-LAST:event_TitleMouseDragged

    private void red_squrMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_red_squrMousePressed
        System.exit(0);
    }// GEN-LAST:event_red_squrMousePressed

    private void red_squrMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_red_squrMouseExited
        red_squr.setBackground(new Color(255, 255, 255));
        exit.setForeground(new Color(102, 102, 102));
    }// GEN-LAST:event_red_squrMouseExited

    private void red_squrMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_red_squrMouseEntered
        red_squr.setBackground(new Color(204, 0, 0));
        exit.setForeground(Color.white);
    }// GEN-LAST:event_red_squrMouseEntered

    private void exitMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_exitMousePressed
        System.exit(0);
    }// GEN-LAST:event_exitMousePressed

    private void exitMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_exitMouseExited
        red_squr.setBackground(new Color(255, 255, 255));
        exit.setForeground(new Color(102, 102, 102));
    }// GEN-LAST:event_exitMouseExited

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_exitMouseEntered
        red_squr.setBackground(new Color(204, 0, 0));
        exit.setForeground(Color.white);
    }// GEN-LAST:event_exitMouseEntered

    private void btn_sustentoMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_sustentoMousePressed

    }// GEN-LAST:event_btn_sustentoMousePressed

    private void btn_sustentoMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_sustentoMouseExited

    }// GEN-LAST:event_btn_sustentoMouseExited

    private void btn_sustentoMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_sustentoMouseEntered

    }// GEN-LAST:event_btn_sustentoMouseEntered

    private void btn_requisitosMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_requisitosMousePressed

    }// GEN-LAST:event_btn_requisitosMousePressed

    private void btn_requisitosMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_requisitosMouseExited

    }// GEN-LAST:event_btn_requisitosMouseExited

    private void btn_requisitosMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_requisitosMouseEntered
        if (btn_requisitos.getBackground().getRGB() == -15574355) {
            setColor(btn_requisitos);
        }
    }// GEN-LAST:event_btn_requisitosMouseEntered

    private void btn_datosAcademicosMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_datosAcademicosMousePressed

    }// GEN-LAST:event_btn_datosAcademicosMousePressed

    private void btn_datosAcademicosMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_datosAcademicosMouseExited

    }// GEN-LAST:event_btn_datosAcademicosMouseExited

    private void btn_datosAcademicosMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_datosAcademicosMouseEntered

    }// GEN-LAST:event_btn_datosAcademicosMouseEntered

    private void btn_personalesMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_personalesMousePressed

    }// GEN-LAST:event_btn_personalesMousePressed

    private void btn_personalesMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_personalesMouseExited

    }// GEN-LAST:event_btn_personalesMouseExited

    private void btn_personalesMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_personalesMouseEntered

    }// GEN-LAST:event_btn_personalesMouseEntered

    private void btn_personalesMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_personalesMouseClicked

    }// GEN-LAST:event_btn_personalesMouseClicked

    private void btn_datosAcademicosMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_datosAcademicosMouseClicked

    }// GEN-LAST:event_btn_datosAcademicosMouseClicked

    private void btn_requisitosMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_requisitosMouseClicked

    }// GEN-LAST:event_btn_requisitosMouseClicked

    private void btn_sustentoMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_sustentoMouseClicked

    }// GEN-LAST:event_btn_sustentoMouseClicked

    public void volverAlPanel(JPanel panel, String panel1) {
        pnl_vistaPrincipal.add(panel, panel1);
        vista.show(pnl_vistaPrincipal, panel1);
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }

    void setColor(JPanel panel) {
        panel.setBackground(new Color(21, 101, 192));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(18, 90, 173));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new PanelEst().setVisible(true);
            }
        });
    }

    public void mostrarPanel(String nombrePanel) {
        CardLayout cardLayout = (CardLayout) pnl_vistaPrincipal.getLayout();
        cardLayout.show(pnl_vistaPrincipal, nombrePanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Title;
    private javax.swing.JLabel app_name;
    private javax.swing.JPanel btn_requisitos;
    private javax.swing.JPanel btn_verificar;
    private javax.swing.JLabel exit;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnl_vistaPrincipal;
    private javax.swing.JPanel red_squr;
    // End of variables declaration//GEN-END:variables
}
